### ISSUE TITLE
Error while building the singularity image

### ISSUE THREAD

**Issue by JuliaR1** [matmu/vep#1]
Sometimes an error occurs while building the singularity image:

Downloaded layer sha256:94da6cf6f5118f7b1daab46ec4470d1f17ef914933c005fd963f718c0c4c9424.tar.gz does not match checksum
Error during layer download - one or more layers failed to download correctly.

**Comment by matmu** [comment]
This can be solved by trying to build again some time later. Probably an issue with hub.docker.com
